<a href="https://colab.research.google.com/github/MariaMoreira04/ia_colabGoogleMaria/blob/main/IA_ACT2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
listTemp=list()
listTemp.append(-1)
listTemp.append(0)
listTemp.append(1)

print('My list: {}'.format(listTemp))

def positiveNegative(number):
  if number<0:
    print('Negative')
  elif number>0:
    print('Positive')
  else:
      print('Zero')
  pass

for item in listTemp:
  positiveNegative(item)

# number=listTemp[1]
# print('which one: ',number)
# positiveNegative(number)

My list: [-1, 0, 1]
Negative
Zero
Positive


In [ ]:
class persons():
  def __init__(self,name,age):
    self.name=name
    self.age=age

  def message(self):
      print('Hola, {}'.format(self.name))
      print('your age is, {}'.format(self.age))

person1=persons('María', 21)
person2=persons('Maryangel', 21)
person3=persons('Jaritza', 22)
person4=persons('Jose', 15)
person5=persons('Pedro', 18)

person1.message()

Hola, María
your age is, 21


In [ ]:
import numpy as Joselito
a=Joselito.array([1,2,3])
print(a)
print(a.shape)
print(type[a])
print('1 dimesion : ',a[1])

import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b)
print('number 5 : ',b[1,1])

print('------')
c=np.zeros((3,4),dtype=float)
print(c)

c=np.ones((3,4),dtype=float)
print(c)
print('----------')
c=np.eye(5)
print(c)




[1 2 3]
(3,)
type[array([1, 2, 3])]
1 dimesion :  2
(2, 3)
[[1 2 3]
 [4 5 6]]
number 5 :  5
------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
----------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
d=np.random.randn(4,4)
print(d)

[[ 0.46138123  1.56671819  0.69497102 -1.28313517]
 [-0.63882143  0.02036881  1.44421909 -0.03531729]
 [-1.75839279 -0.99111974 -1.16699903 -1.65348935]
 [-0.74236149 -0.44084895  1.41057231  1.24219495]]


Sacar copia del arreglo original

In [ ]:
d=10*np.random.randn(4,4)
print(d)

[[-15.12425492   2.67249704  25.17037317   2.37053574]
 [-15.44894099   5.57054916  21.5167645    5.81791639]
 [ -7.02375272  10.21400579   2.95377506  18.00447265]
 [  2.62997683  -5.53345212   8.71981676 -12.43283258]]


In [ ]:
print(d[2,2])
tmp=np.array(d)
tmp[2,2]=150
print(tmp[2,2])

2.953775057589467
150.0


In [ ]:
d=10*np.random.randn(5,5)
print(d)

[[-27.46002461  10.63279116  -0.46302189   7.31081367  -3.50294412]
 [-12.97257656   8.46591462   5.16502914   7.33355757  -2.58175555]
 [ 12.88330165 -19.38486927  -5.60948927   3.86357498  15.69340016]
 [ 14.50643823   1.67375987  13.34668756  -8.19678926 -17.93631138]
 [  3.86525401   6.03669373  -7.05612965  13.46627095 -11.47140285]]


Generar copia personalizada

In [ ]:
tmp=np.array(d[1:4,1:4])
print(tmp)
print(tmp.shape)

[[  8.46591462   5.16502914   7.33355757]
 [-19.38486927  -5.60948927   3.86357498]
 [  1.67375987  13.34668756  -8.19678926]]
(3, 3)


In [ ]:
tmp=np.array(d[:,1:4])
print(tmp)
print(tmp.shape)

[[ 10.63279116  -0.46302189   7.31081367]
 [  8.46591462   5.16502914   7.33355757]
 [-19.38486927  -5.60948927   3.86357498]
 [  1.67375987  13.34668756  -8.19678926]
 [  6.03669373  -7.05612965  13.46627095]]
(5, 3)


MATRIZ DE VALORES BOOLEANOS

In [ ]:
mask=d>10.0
print(d.shape)
print(mask)
print(type(mask))

tmp=d[mask]
print('Values: {}'.format(tmp))
print(type(tmp))
print(tmp.shape)

print(tmp[1])

(5, 5)
[[False  True False False False]
 [False False False False False]
 [ True False False False  True]
 [ True False  True False False]
 [False False False  True False]]
<class 'numpy.ndarray'>
Values: [10.63279116 12.88330165 15.69340016 14.50643823 13.34668756 13.46627095]
<class 'numpy.ndarray'>
(6,)
12.883301650660883


OPERACIONES:

In [ ]:
a=10*np.random.randn(3,3)

b=10*np.random.randn(3,3)
print(a)
print('')
print(b)

[[-15.55132631 -16.53514201   1.05859696]
 [ 10.88995544  -8.57217421  -3.85591382]
 [  1.03649161  15.8368899   24.457728  ]]

[[ -8.15321376   0.86452827  11.43468039]
 [  5.00139199   8.223501     7.16799772]
 [-22.59222769  11.15096254 -14.33819943]]


SUMA

In [ ]:
print(a+b)

[[-23.70454008 -15.67061374  12.49327736]
 [ 15.89134743  -0.34867321   3.3120839 ]
 [-21.55573608  26.98785244  10.11952857]]


In [ ]:
print(np.add(a,b))

[[-23.70454008 -15.67061374  12.49327736]
 [ 15.89134743  -0.34867321   3.3120839 ]
 [-21.55573608  26.98785244  10.11952857]]


POTENCIA

In [ ]:
c=np.array([[1,2],[2,4]])
print(c.shape)
print(c)

print('----')
# ELEVAR AL CUADRADO
print(np.square(c))
# ELEVAR AL CUBO
print(np.power(c,3))

(2, 2)
[[1 2]
 [2 4]]
----
[[ 1  4]
 [ 4 16]]
[[ 1  8]
 [ 8 64]]


In [ ]:
c=10*np.random.rand(3,4)
print(c)


[[2.95229358 4.07890652 1.41314258 0.9825092 ]
 [0.55244642 3.75922755 9.8891209  4.54694929]
 [7.65346033 5.90103768 9.4411905  1.02259135]]


In [ ]:
# print(c.mean(axis=0))
# # print(c.mean(axis=1))

In [ ]:
# # print(c.mean(axis=0))
# print(c.mean(axis=1))

In [ ]:
c=10*np.random.rand(3,3)
h=10*np.random.rand(3,3)
print(c)
print()
print(h)

[[0.55540914 2.00484688 5.66790313]
 [4.92895382 8.30881069 5.38005053]
 [9.60877156 7.43490466 6.52395269]]

[[4.13972092 2.15992486 2.04635853]
 [1.54098631 7.85155895 3.68581031]
 [4.97344203 1.47255908 3.69951264]]


In [ ]:
# VERTICAL
yl=np.vstack((c,h))
print(yl)

print('----')
# HORIZONTAL
yl=np.hstack((c,h))
print(yl)

[[0.55540914 2.00484688 5.66790313]
 [4.92895382 8.30881069 5.38005053]
 [9.60877156 7.43490466 6.52395269]
 [4.13972092 2.15992486 2.04635853]
 [1.54098631 7.85155895 3.68581031]
 [4.97344203 1.47255908 3.69951264]]
----
[[0.55540914 2.00484688 5.66790313 4.13972092 2.15992486 2.04635853]
 [4.92895382 8.30881069 5.38005053 1.54098631 7.85155895 3.68581031]
 [9.60877156 7.43490466 6.52395269 4.97344203 1.47255908 3.69951264]]
