<a href="https://colab.research.google.com/github/MariaMoreira04/ia_colabGoogleMaria/blob/main/TareaEjerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


 1. Import numpy as np and see the version

In [3]:
import numpy as np
print(np.__version__)
pass

1.22.4


2. Create a 1D array of numbers from 0 to 9


In [5]:
array_1d = np.arange(10)
print(array_1d)
pass

[0 1 2 3 4 5 6 7 8 9]


 3. Create a 3×3 numpy array of all True’s


In [6]:
array = np.ones((3, 3), dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


 4. Extract all odd numbers from arr

In [12]:
arr = np.array([[12, 1, 5], [25, 10, 2], [4, 7, 3]])
odd_nums = arr[arr % 2 == 1]
print(odd_nums)

[ 1  5 25  7  3]


5. Replace all odd numbers in arr with -1

In [13]:
mask = arr % 2 == 1
arr[mask] = -1
print(arr)

[[12 -1 -1]
 [-1 10  2]
 [ 4 -1 -1]]


6. Convert a 1D array to a 2D array with 2 rows

In [17]:
# Example 1D array
arr_1d = np.array([6, 2, 1, 4, 5, 3])

# Reshape the array to a 2D array with 2 rows
arr_2d = arr_1d.reshape(2, -1)

# Print the result
print(arr_2d)

[[6 2 1]
 [4 5 3]]


7. Stack arrays a and b vertically

In [22]:
a = np.array([[10, 4, 1], [5, 6, 2]])
b = np.array([[1, 3, 8], [2, 12, 18]])
c = np.vstack((a, b))
print(c)

[[10  4  1]
 [ 5  6  2]
 [ 1  3  8]
 [ 2 12 18]]


8. Stack the arrays a and b horizontally.

In [24]:
a = np.array([[10, 4, 1], [5, 6, 2]])
b = np.array([[1, 3, 8], [2, 12, 18]])
c = np.hstack((a, b))
print(c)

[[10  4  1  1  3  8]
 [ 5  6  2  2 12 18]]


9. Get all items between 5 and 10 from a.

In [31]:
a = np.array([20, 18, 15, 10, 5, 3, 6])
mask = (a <= 10) & (a>= 5 )
result = a[mask]

print(result)

[10  5  6]


#  10. How to make a python function that handles scalars to work on numpy arrays?


In [33]:
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

def pair_max(a, b):
    return np.maximum(a, b)

# Example usage
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print(result)

[6 7 9 8 9 7 5]



#  11. Swap columns 1 and 2 in the array arr.


In [34]:
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]

# Given array
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

# Swap columns 1 and 2
arr[:, [0, 1]] = arr[:, [1, 0]]

print(arr)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


#  12. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.


In [35]:
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]


array = np.random.uniform(low=5, high=10, size=(5,3))

print(array)

[[7.24660769 9.92690766 5.38964449]
 [8.12077257 8.58391562 9.99925153]
 [8.79662388 6.51751292 7.03233578]
 [7.49847044 5.18792204 8.04722097]
 [9.08795487 7.38268326 9.08747404]]


BY MARIA MERCEDES MOREIRA VÉLEZ-INTELIGENCIA ARTIFICIAL-8°SEMESTRE